import Head from "next/head"
import Hero from "@/components/Hero"
import Testimonials from "@/components/Testimonials"
import ContactForm from "@/components/ContactForm"
import Services from "@/components/Services"
import Benefits from "@/components/Benefits"

export default function Home() {
    return (
        <>
            <Head>
                <title>CryoLabz</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <div>
                    <Hero />
                    <Services />
                    <Benefits />
                    <Testimonials />
                    <ContactForm />
                </div>
            </main>
        </>
    )
}
