import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import Hero from "@/components/Hero"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>CryoLabz</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-full h-screen bg-purple-100">
                <div>
                    <h2>CryoLabz</h2>
                    <Hero />
                </div>
            </main>
        </>
    )
}
